In [1]:
import re
import numpy as np

In [2]:
with open('sentences.txt', 'r') as fp:  
    content=fp.readlines()
    content = [x.strip().lower() for x in content]             

In [3]:
set1=set();
for x in content:
    test = re.split('[^a-z]',x)
    for a in test:
        if a!='':
            set1.add(a)  
dictionary = list(sorted(set1))

In [4]:
matrix=np.zeros((len(set1),len(content)))
print(matrix)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
cnt=0
for x in content:   
    test=re.split('[^a-z]',x)
    for st in test:
        if st!='':
            j=cnt
            i=dictionary.index(st)
            matrix[i, j]+=1
            #print(i)
            #print(j)
            #print(matrix[i, j])
    cnt+=1


In [6]:
print matrix[0] 
print(dictionary[0])

[0. 0. 3. 0. 1. 0. 0. 0. 1. 2. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
a


In [7]:
print matrix[:,1]

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0.
 0. 2. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
from scipy.spatial.distance import cosine as cos

In [9]:
cos_distance =  []



In [10]:
for i in range(0, 22):
    number = cos(matrix[:,0], matrix[:,i])
    cos_distance += [number]
print(cos_distance)




[0.0, 0.9527544408738466, 0.8644738145642124, 0.8951715163278082, 0.7770887149698589, 0.9402385695332803, 0.7327387580875756, 0.9258750683338899, 0.8842724875284311, 0.9055088817476932, 0.8328165362273942, 0.8804771390665607, 0.8396432548525454, 0.8703592552895671, 0.8740118423302576, 0.9442721787424647, 0.8406361854220809, 0.956644501523794, 0.9442721787424647, 0.8885443574849294, 0.8427572744917122, 0.8250364469440588]


In [11]:
sorted_distance=sorted(cos_distance)

In [12]:
print(sorted_distance)

[0.0, 0.7327387580875756, 0.7770887149698589, 0.8250364469440588, 0.8328165362273942, 0.8396432548525454, 0.8406361854220809, 0.8427572744917122, 0.8644738145642124, 0.8703592552895671, 0.8740118423302576, 0.8804771390665607, 0.8842724875284311, 0.8885443574849294, 0.8951715163278082, 0.9055088817476932, 0.9258750683338899, 0.9402385695332803, 0.9442721787424647, 0.9442721787424647, 0.9527544408738466, 0.956644501523794]


In [17]:
cos1=sorted_distance[1]
cos2=sorted_distance[2]
answer = [cos_distance.index(cos1), cos_distance.index(cos2)]
answer = sorted(answer)
print(answer)

[4, 6]


In [19]:
f = open('submission-1.txt', 'w')
f.write(str(answer[0])+" "+str(answer[1]))
f.close()